---
services:
  sdeul:
    container_name: sdeul
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/sdeul:latest
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/sdeul
    command:
      - --version
