[tool.poetry]
name = "sdeul"
version = "0.1.0"
description = "Structural Data Extractor using LLMs"
authors = ["dceoy <dnarsil+github@gmail.com>"]
license = "GNU Affero General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
docopt = "^0.6.2"
jsonschema = "^4.20.0"
langchain = "^0.0.349"
llama-cpp-python = "^0.2.22"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "^6.1.0"
flake8-bugbear = "^23.12.2"
flake8-isort = "^6.1.1"
pep8-naming = "^0.13.3"
mypy = "^1.7.1"
types-docopt = "^0.6.11.4"
types-jsonschema = "^4.20.0.0"
types-setuptools = "^69.0.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
